# Generated by Django 6.0 on 2025-12-11 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_users_username_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_department', to='adminapp.department'),
        ),
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('total_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'present'), ('unpaid_leave', 'unpaid_leave'), ('paid_leave', 'paid_leave'), ('half_day', 'half_day'), ('incomplete_hours', 'incomplete_hours'), ('pending', 'pending')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('casual', 'casual'), ('sick', 'sick'), ('maternity', 'maternity'), ('privilege ', 'privilege '), ('other', 'other')], default='other', max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
