# Generated by Django 6.0 on 2025-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_users_department_users_profile_attendance_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
