# Generated by Django 6.0 on 2025-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_users_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
