# Generated by Django 6.0 on 2025-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_user_leave_employee_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'from_date', 'to_date'], name='adminapp_le_employe_15d5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status'], name='adminapp_le_status_25ae7c_idx'),
        ),
    ]
