# Generated by Django 6.0 on 2025-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_leave_adminapp_le_employe_15d5ce_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
