# Generated by Django 6.0 on 2025-12-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_position_remove_users_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to='adminapp.position'),
        ),
    ]
