# Generated by Django 6.0 on 2025-12-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_users_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
