# Generated by Django 6.0 on 2025-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
