# Generated by Django 5.2.9 on 2025-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
