# Generated by Django 5.2.9 on 2026-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_notification_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, default="/", max_length=500),
        ),
    ]
