# Generated by Django 5.2.9 on 2026-02-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_alter_notification_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceToken",
        ),
    ]
