# Generated by Django 5.2.9 on 2026-02-27 11:14

from django.db import migrations, models

import apps.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0008_delete_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtype",
            name="code",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
    ]
