# Generated by Django 5.2.9 on 2025-12-16 10:20

import apps.superadmin.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', apps.superadmin.managers.UserManager()),
            ],
        ),
    ]
