# Generated by Django 5.2.9 on 2025-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0004_alter_users_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pl_leave", models.IntegerField(blank=True, default=12, null=True)),
                ("sl_leave", models.IntegerField(blank=True, default=4, null=True)),
                ("lop_leave", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
