# Generated by Django 5.2.9 on 2025-12-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0005_commondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_host", models.CharField(blank=True, max_length=255, null=True)),
                ("email_port", models.IntegerField(blank=True, null=True)),
                (
                    "email_host_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_host_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_use_tls", models.BooleanField(default=True)),
                ("email_use_ssl", models.BooleanField(default=False)),
                (
                    "database_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "database_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "database_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "database_host",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "database_port",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_zone", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token_lifetime", models.IntegerField(default=1)),
                ("refresh_token_lifetime", models.IntegerField(default=7)),
                (
                    "celery_broker_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "celery_result_backend",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
