# Generated by Django 5.2.9 on 2025-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0006_settingdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("casual", "casual"),
                    ("sick", "sick"),
                    ("maternity", "maternity"),
                    ("privilege", "privilege"),
                    ("other", "other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
