# Generated by Django 5.2.9 on 2025-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0007_alter_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="commondata",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logo"),
        ),
    ]
