# Generated by Django 5.2.9 on 2025-12-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0008_commondata_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="leave",
            name="leave_type",
        ),
    ]
