# Generated by Django 5.2.9 on 2025-12-31 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0009_leavetype_remove_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_type",
                to="superadmin.leavetype",
            ),
        ),
    ]
