# Generated by Django 5.2.9 on 2025-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0010_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="day_part",
            field=models.CharField(
                blank=True,
                choices=[("first", "First"), ("second", "Second")],
                max_length=50,
                null=True,
            ),
        ),
    ]
