# Generated by Django 5.2.9 on 2025-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0011_leave_day_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="total_days",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
