# Generated by Django 5.2.9 on 2026-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("superadmin", "0013_announcement_deleted_at_announcement_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(fields=["email"], name="superadmin__email_9ecea7_idx"),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["employee_id"], name="superadmin__employe_093824_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["role", "is_active"], name="superadmin__role_aecbbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["department"], name="superadmin__departm_b40432_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="users",
            index=models.Index(
                fields=["birthdate"], name="superadmin__birthda_ed53a6_idx"
            ),
        ),
    ]
