# Generated by Django 5.2.9 on 2026-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0014_alter_users_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="salary_ctc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
