# Generated by Django 5.2.9 on 2026-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0015_users_salary_ctc"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="is_sandwich_applied",
            field=models.BooleanField(default=False),
        ),
    ]
