# Generated by Django 5.2.9 on 2026-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0016_leave_is_sandwich_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="commondata",
            name="handbook_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commondata",
            name="handbook_content_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commondata",
            name="handbook_file",
            field=models.FileField(blank=True, null=True, upload_to="handbook_file"),
        ),
        migrations.AddField(
            model_name="commondata",
            name="handbook_last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="commondata",
            name="policy_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commondata",
            name="policy_content_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commondata",
            name="policy_file",
            field=models.FileField(blank=True, null=True, upload_to="policy_file"),
        ),
        migrations.AddField(
            model_name="commondata",
            name="policy_last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
