# Generated by Django 5.2.9 on 2026-02-16 09:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0018_deviceactivity_userdevicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevicetoken",
            name="tracking_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
