# Generated by Django 5.2.9 on 2026-02-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0020_deviceconfigpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceconfigpolicy",
            name="server_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
