# Generated by Django 5.2.9 on 2026-02-27 10:45

from django.db import migrations, models

import apps.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0021_deviceconfigpolicy_server_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
    ]
