# Generated by Django 5.2.9 on 2026-02-27 11:14

from django.db import migrations, models

import apps.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0022_alter_holiday_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="date",
            field=models.DateTimeField(
                validators=[apps.base.validators.BaseValidator.validate_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="deviceconfigpolicy",
            name="key",
            field=models.CharField(
                default="default",
                max_length=50,
                unique=True,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="date",
            field=models.DateField(
                validators=[apps.base.validators.BaseValidator.validate_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="day_part",
            field=models.CharField(
                blank=True,
                choices=[("first", "First"), ("second", "Second")],
                max_length=50,
                null=True,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                default="pending",
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="code",
            field=models.CharField(
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="employee_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                blank=True,
                default="employee",
                max_length=50,
                null=True,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
    ]
