# Generated by Django 5.2.9 on 2026-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0024_client_project_dailyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
