# Generated by Django 5.2.9 on 2026-03-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0025_alter_client_country_alter_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="encryption_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether encryption is enabled for this user"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="public_key",
            field=models.TextField(
                blank=True,
                help_text="User's public key for E2E encryption (base64-encoded)",
                null=True,
            ),
        ),
    ]
