# Generated by Django 5.2.9 on 2026-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0026_users_encryption_enabled_users_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="encryption_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
