# Generated by Django 5.2.9 on 2025-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.IntegerField(blank=True, default=12, null=True)),
                ('sl', models.IntegerField(blank=True, default=4, null=True)),
                ('lop', models.IntegerField(blank=True, default=0, null=True)),
                ('year', models.IntegerField(blank=True, default=2025, null=True)),
            ],
        ),
    ]
