# Generated by Django 6.0 on 2025-12-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_leavebalance_lop_alter_leavebalance_pl_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='employee_le_employe_bff7bc_idx',
        ),
    ]
