# Generated by Django 5.2.9 on 2025-12-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="leave_deductions",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
