# Generated by Django 5.2.9 on 2025-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_payslip_leave_deductions"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="used_lop",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="used_pl",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="used_sl",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
