# Generated by Django 5.2.9 on 2025-12-18 11:38

from django.db import migrations, models

import apps.employee.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_leavebalance_used_lop_leavebalance_used_pl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(
                blank=True, default=apps.employee.models.current_year, null=True
            ),
        ),
    ]
