# Generated by Django 5.2.9 on 2025-12-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_alter_leavebalance_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
