# Generated by Django 5.2.9 on 2025-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_leavebalance_id_alter_payslip_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="payslips/"),
        ),
    ]
