# Generated by Django 5.2.9 on 2025-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_payslip_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="lop",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="pl",
            field=models.FloatField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="sl",
            field=models.FloatField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="used_lop",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="used_pl",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="used_sl",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="days",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
