# Generated by Django 5.2.9 on 2025-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_leavebalance_lop_alter_leavebalance_pl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payslip",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
