# Generated by Django 5.2.9 on 2026-01-01 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_leavebalance_deleted_at_leavebalance_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(
                fields=["employee", "year"], name="employee_le_employe_bff7bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["year"], name="employee_le_year_c90c8e_idx"),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["employee", "month"], name="employee_pa_employe_8eb26a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_pa_start_d_aea0e8_idx"
            ),
        ),
    ]
