# Generated by Django 5.2.9 on 2026-01-01 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0012_leavebalance_employee_le_employe_bff7bc_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="leavebalance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("employee", "year"),
                name="unique_active_employee_per_year",
            ),
        ),
    ]
