# Generated by Django 5.2.9 on 2026-02-27 11:14

from django.db import migrations, models

import apps.base.validators
import apps.employee.models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_alter_leavebalance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="year",
            field=models.IntegerField(
                blank=True,
                default=apps.employee.models.current_year,
                null=True,
                validators=[
                    apps.base.validators.BaseValidator.validate_positive_number
                ],
            ),
        ),
    ]
