# Generated by Django 5.2.9 on 2026-03-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0015_item_inventorydetail_ticketissue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavebalance",
            name="pl",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="sl",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
