# Generated by Django 5.2.9 on 2026-03-26 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0016_alter_leavebalance_pl_alter_leavebalance_sl"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("returned", "Returned"),
                            ("maintenance", "Maintenance"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="inventorydetail",
            name="employee_in_employe_0eeee6_idx",
        ),
        migrations.RemoveField(
            model_name="inventorydetail",
            name="alloted_by",
        ),
        migrations.RemoveField(
            model_name="inventorydetail",
            name="allotment_date",
        ),
        migrations.RemoveField(
            model_name="inventorydetail",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="inventorydetail",
            name="quantity",
        ),
        migrations.AddField(
            model_name="inventorydetail",
            name="condition",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AddField(
            model_name="inventorydetail",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorydetail",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="inventorydetail",
            name="status",
            field=models.CharField(default="available", max_length=20),
        ),
        migrations.AddIndex(
            model_name="inventorydetail",
            index=models.Index(fields=["item"], name="employee_in_item_id_98471c_idx"),
        ),
        migrations.AddField(
            model_name="itemassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="itemassignment",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.inventorydetail",
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemhistory",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.inventorydetail",
            ),
        ),
    ]
