# Generated by Django 5.2.9 on 2025-12-16 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancebreaklogs",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_break_logs",
                to="attendance.employeeattendance",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeattendance",
            index=models.Index(
                fields=["employee", "day"], name="attendance__employe_0c0437_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together={("employee", "day")},
        ),
    ]
