# Generated by Django 5.2.9 on 2026-01-01 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancebreaklogs_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employeeattendance",
            index=models.Index(
                fields=["day", "status"], name="attendance__day_fe6ae9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeattendance",
            index=models.Index(
                fields=["check_in"], name="attendance__check_i_46c128_idx"
            ),
        ),
    ]
