# Generated by Django 5.2.9 on 2026-01-01 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_employeeattendance_attendance__day_fe6ae9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeeattendance",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="employeeattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("employee", "day"),
                name="unique_active_attendance_per_day",
            ),
        ),
    ]
