# Generated by Django 5.2.9 on 2026-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_employeeattendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="is_halfday_paid",
            field=models.BooleanField(default=False),
        ),
    ]
