# Generated by Django 5.2.9 on 2026-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_employeeattendance_is_halfday_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="current_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
