# Generated by Django 5.2.9 on 2026-02-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_employeeattendance_current_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeattendance",
            name="current_time",
        ),
    ]
