# Generated by Django 5.2.9 on 2026-02-27 11:14

from django.db import migrations, models

import apps.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_remove_employeeattendance_current_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "present"),
                    ("unpaid_leave", "unpaid_leave"),
                    ("paid_leave", "paid_leave"),
                    ("half_day", "half_day"),
                    ("incomplete_hours", "incomplete_hours"),
                    ("pending", "pending"),
                ],
                default="pending",
                max_length=50,
                validators=[apps.base.validators.BaseValidator.validate_name],
            ),
        ),
    ]
