# Generated by Django 5.2.9 on 2026-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_employeeattendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeattendance",
            name="is_early_going",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="is_late_coming",
            field=models.BooleanField(default=False),
        ),
    ]
