# Generated by Django 5.2.9 on 2026-01-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiquerylog",
            name="ai_message",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_message_queries",
                to="ai.aimessage",
            ),
            preserve_default=False,
        ),
    ]
