# Generated by Django 5.2.9 on 2026-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aiquerylog_ai_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiquerylog",
            name="intent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
