# Generated by Django 5.2.9 on 2026-02-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_aiquerylog_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiquerylog",
            name="intent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
