# Generated by Django 5.2.9 on 2026-02-27 11:14

from django.db import migrations, models

import apps.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_aiquerylog_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiquerylog",
            name="response_quality",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    apps.base.validators.BaseValidator.validate_positive_number
                ],
            ),
        ),
    ]
