# Generated by Django 6.0 on 2025-12-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_alter_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedailylogs',
            name='attendance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceDailyLogs',
        ),
    ]
