# Generated by Django 5.2.9 on 2025-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_reply_to_messagereaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
