# Generated by Django 5.2.9 on 2026-01-01 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_conversation_deleted_at_conversation_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["type"], name="chat_conver_type_857bd7_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["created_at"], name="chat_conver_created_656b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender"], name="chat_messag_sender__c4389c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["msg_type"], name="chat_messag_msg_typ_b94052_idx"
            ),
        ),
    ]
