# Generated by Django 5.2.9 on 2026-01-01 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_conversation_chat_conver_type_857bd7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="messagestatus",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("message", "user", "emoji"),
                name="unique_active_emoji_per_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagestatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("message", "user"),
                name="unique_active_message_per_user",
            ),
        ),
    ]
