# Generated by Django 5.2.9 on 2026-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_message_is_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="conversation_profiles/"
            ),
        ),
    ]
