# Generated by Django 5.2.9 on 2026-03-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_conversation_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="encrypted_text",
            field=models.TextField(
                blank=True,
                help_text="Base64-encoded encrypted message content",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_encrypted",
            field=models.BooleanField(
                default=False, help_text="Whether this message is encrypted"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="nonce",
            field=models.CharField(
                blank=True,
                help_text="Base64-encoded nonce for encryption",
                max_length=32,
                null=True,
            ),
        ),
    ]
